version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  build:
      docker:
        - image: cimg/base:2020.01
      steps:
        - checkout
        - run:
            name: "echo an env var that is part of our project"
            command: |
              echo $MY_ENV_VAR
  # say_hello:
  #   docker:
  #    - image: cimg/base:stable
  #   steps:
  #    - checkout
  #    - run: echo welcome

  # print_hello:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run: echo hello

  # print_world:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run: echo world

  


workflows:
  # welcome:
  test-env-vars:
    jobs:
     - build
    #  - say_hello
    #  - print_hello:
    #       requires: [say_hello]
    #  - print_world:
    #       requires: [say_hello,print_hello] 