version: 2.1
jobs:
  say_hello:
    docker:
     - image: cimg/base:stable
    steps:
     - checkout
     - run:
          name: "say_hello"
          command: "echo hello,world!" 
  print-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "print_hello"
          command: "echo hello"
  print_world:
    docker:
      - image: cimh/base:stable
    steps:
     - checkout
     - run:
           name: "print_world"
           command: "echo world"      
workflows:
  welcome:
    jobs:
    - welcome/run
    - say_hello
    - print_hello
    - print_world
       requires:
        - say_hello